#!/usr/bin/env python3
# Copyright 2026 Democratized Data Foundation
#
# This file is part of the DefraDB test suite.
#
# The DefraDB test suite is licensed under either:
#
#   (1) GNU Affero General Public License v3
#   (2) Business Source License 1.1
#
# See tests/LICENSE for details.
"""Emit a docker-compose file for an N-node benchnode stack on one bridge network.

The committed docker-compose.yml is a hand-written 2-node pair; this generates the
same shape for arbitrary N so the multi-node topologies (star/line/mesh over 5, 10
nodes) can run as real containers on a single host. Each node publishes its control
API on 127.0.0.1:(17701+i) and keeps p2p (9300) internal to the bridge, exactly like
the pair. $RECON selects the mode (--reconciliation for ranges, empty for default).

Usage: python3 gen-compose.py N > docker-compose.N.yml
"""

import sys

CONTROL_BASE = 17701  # host-published control port for node0; node i -> CONTROL_BASE+i


def service(i):
    return f"""  node{i}:
    image: benchnode:local
    entrypoint: ["sh", "-c"]
    command: ["benchnode --control 0.0.0.0:17700 --p2p /ip4/0.0.0.0/tcp/9300 --store badger=/data ${{RECON-}}"]
    ports:
      - "127.0.0.1:{CONTROL_BASE + i}:17700"
    volumes:
      - node{i}-data:/data
    networks: [benchnet]
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:17700/peerinfo"]
      interval: 2s
      timeout: 3s
      retries: 30
"""


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-compose.py N")
    n = int(sys.argv[1])
    if n < 2:
        sys.exit("N must be >= 2")

    services = "\n".join(service(i) for i in range(n))
    volumes = "\n".join(f"  node{i}-data:" for i in range(n))
    print(f"""# GENERATED by gen-compose.py — {n} benchnodes on one host bridge.
# Do not edit by hand; regenerate with `python3 gen-compose.py {n}`.
name: benchnode-crossdevice

services:
{services}
volumes:
{volumes}

networks:
  benchnet:
    driver: bridge""")


if __name__ == "__main__":
    main()
